### ISSUE TITLE
Problem with action() method

### ISSUE THREAD

**Issue by ghost** [rrb3942/perl-Asterisk-AMI#1]
Hi, this is my first post here! The problem is that method action() won't work inside a sub, that was called for the Handler! When the program come to that method it won't go any further! The method send_action works just fine, when I replaced it on that spot!
Sorry for my rusty English...

**Comment by rrb3942** [comment]
Hello,

It sounds like you are combining event-based programming and blocking calls. This is problematic in general. A code example of what you are doing might make this more clear. 

There is a big ol' warning in the documentation about this http://search.cpan.org/~greenbean/Asterisk-AMI-v0.2.0/lib/Asterisk/AMI.pm#Warning_-_Mixing_Event-loops_and_blocking_actions

My suggestion would be to to use send_action and use a callback subroutine to process the response.
