### ISSUE TITLE
Error --- unsupported type passed to AnyEvent::Handle::push_read 

### ISSUE THREAD

**Issue by algrims** [rrb3942/perl-Asterisk-AMI#2]
unsupported type passed to AnyEvent::Handle::push_read at /usr/local/lib/perl5/site_perl/5.10.0/Asterisk/AMI.pm line 788

I have the latest version of AnyEvent -

FYI - I am running asterisk 1.6

**Comment by rrb3942** [comment]
I am having trouble replicating this. It seems like either AnyEvent cannot find the Asterisk::AMI Module, or that it cannot accept a package name in push_read. Could  you please provide the output from the following commands:

perl -v
perl -MAnyEvent -e 'print "$AnyEvent::VERSION\n"'
perl -MAnyEvent::Handle -e 'print "$AnyEvent::Handle::VERSION\n"'
perl -MAsterisk::AMI -e 'print "$Asterisk::AMI::VERSION\n"'
perl -e 'foreach (@INC){print $_,"\n"}'

**Comment by algrims** [comment]
perl -v

This is perl, v5.10.0 built for i386-linux-thread-multi

Copyright 1987-2007, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

**Comment by algrims** [comment]
perl -MAnyEvent -e 'print "$AnyEvent::VERSION\n"'
5.112

**Comment by algrims** [comment]
perl -MAnyEvent::Handle -e 'print "$AnyEvent::Handle::VERSION\n"'
5.112

**Comment by algrims** [comment]
perl -MAsterisk::AMI -e 'print "$Asterisk::AMI::VERSION\n"'
v0.2.0

**Comment by algrims** [comment]
perl -e 'foreach (@INC){print $_,"\n"}'
/usr/local/lib/perl5/site_perl/5.10.0/i386-linux-thread-multi
/usr/local/lib/perl5/site_perl/5.10.0
/usr/lib/perl5/vendor_perl/5.10.0/i386-linux-thread-multi
/usr/lib/perl5/vendor_perl/5.10.0
/usr/lib/perl5/vendor_perl
/usr/lib/perl5/5.10.0/i386-linux-thread-multi
/usr/lib/perl5/5.10.0
/usr/lib/perl5/site_perl

**Comment by algrims** [comment]
the only thing i see happening is at the CLI:

  == Manager 'alex' logged on from 192.168.4.25
  == Manager 'alex' logged off from 192.168.4.25

**Comment by rrb3942** [comment]
I think I see the problem. You have AnyEvent version 5.112. We are using a feature that was introduced in 5.2 (5.112 is better read as 5.1.1.2). Please update to at least version 5.2 of AnyEvent. The current is 5.271.

I will be updating the module requirements to specify a version of AnyEvent >= 5.2.

Pertinent Parts from the AnyEvent Changelog:

5.2  Mon Sep 14 07:04:49 CEST 2009
    - INCOMPATIBLE CHANGE: do no longer support register_read_type
          and register_write_type in AnyEvent::Handle, instead support
          package names (the facility was mostly abused).
        - implement "packagename-as-read/write type" support in
          AnyEvent::Handle.

Please update AnyEvent and then verify if that fixes the problem or not.

Thanks!

**Comment by algrims** [comment]
Thanks - it looks like it solved it after I upgraded..

Now I get another error after trying to run your sample code.   Try running it.

error:Use of uninitialized value in subroutine entry at /usr/local/lib/perl5/site_perl/5.10.0/Asterisk/AMI.pm line 1406.
    (in cleanup) Can't use string ("") as a subroutine ref while "strict refs" in use at /usr/local/lib/perl5/site_perl/5.10.0/Asterisk/AMI.pm line 1406.

use Asterisk::AMI;

my $astman = Asterisk::AMI->new(PeerAddr        =>      '192.168.4.25',
                                                PeerPort        =>      '5038',
                                                Username        =>      'XXXX',
                                                Secret          =>      'XXXXXX'
                                );
print "Connected\n";

die "Unable to connect to asterisk" unless ($astman);

my $actionid1 = $astman->send_action({  Action => 'Command',
                                                Command => 'sip show peers'
                                });

my $actionid2 = $astman->send_action({  Action => 'Command',
                                       Command => 'sip show peers'
                                });

my $actionid3 = $astman->send_action({  Action => 'Command',
                                       Command => 'sip show peers'
                                });

my $response3 = $astman->get_response($actionid3);
my $response1 = $astman->get_response($actionid1);
my $response2 = $astman->get_response($actionid2);

**Comment by rrb3942** [comment]
Yep, I came across that error as well when I was trying to duplicate your bug. It is caused when the $astman object goes away and we try to flush all pending actions. In this case using get_response when the object was already in the buffer was not fully clearing the callback. It is a fairly harmless error (you can just ignore it if you want), and is fixed on my last push to git. 

You can download the latest source (button to the top right) from this site and the problem should be fixed.

Once I get a chance to run these last few changes through my tests they will be pushed out to CPAN.

I am closing this issue now as the original problem reported is now resolved.

Feel free to open future tickets if you encounter any further issues.

Thanks for your help in identifying these problems!

**Comment by algrims** [comment]
It seems to connect fine now. The only thing is that it does not return anything from the commands.

I see the error on the console;
I will continue to test and let you know.
[2010-06-24 15:22:51] ERROR[13826]: utils.c:1175 ast_careful_fwrite: fwrite() returned error: Broken pipe
[2010-06-24 15:22:51] ERROR[13826]: utils.c:1175 ast_careful_fwrite: fwrite() returned error: Broken pipe

**Comment by rrb3942** [comment]
It is working for me against asterisk 1.6.2.8.

How are you checking the responses?

I recommend using Data::Dumper to print out what is returned to get an idea of how the data is formatted.

use Data::Dumper
...Other Code.....
my $actionid1 = $astman->send_action({  Action => 'Command',
                                        Command => 'sip show peers'});

my $response1 = $astman->get_response($actionid1);
print Dumper $response1;

**Comment by algrims** [comment]
Works like charm!!!!! will keep you informed.  Great application.!

**Comment by algrims** [comment]
More testing of the Asterisk::AMI::Common package.

Monitor works fine and starts recording but StopMonitor does not seem to work.
The recording stops only when the channel is hangup.

What is the outcome of monitoring/stopping monitoring a channel that is already being monitored from the dialplan?  You will have 2 recordings.

I see an issue with monitor, sleep for 10 seconds and stop monitoring. 
It does not stop.  Code sample is below.

Finally, The two files are mixed - distinction between Monitor and MonitorMix?

my $actionid4 = $astman->chan_status($ARGV[0]);
print Dumper $actionid4;

my $actionid4 = $astman->monitor($ARGV[0],"monit223");
print Dumper $actionid4;

sleep(10);

my $actionid4 = $astman->monitor_stop($ARGV[0],1);
print Dumper $actionid4;

**Comment by rrb3942** [comment]
Could you please open this under a new issue and provide the output of those print statements as well?

Thanks for your help.

**Comment by algrims** [comment]
Hello again - I found a workaround.  Sorry for not responding earlier.
I wanted to know how I can disconnect cleanly from the AMI.

**Comment by rrb3942** [comment]
You can call the disconnect() method which attempts a logoff before closing the connection. Or you can just let the asterisk:ami object go out of scope or undefine it as it will attempt a clean logoff before being fully destroyed.

If those methods do not work please open it under a new bug report
