### ISSUE TITLE
AMI disconnecting from asterisk after Originate

### ISSUE THREAD

**Issue by beebeeep** [rrb3942/perl-Asterisk-AMI#3]
Hello.
I'm using Asterisk::AMI in some auto-dialer script and facing some confusing problems with this module trying to keep event-style programming. I'm calling Originate through send_action() and waiting for event with type 'UserEvent', that have to be processed by callback function myHandler() i specified in Asterisk::AMI->new(). The problem is that in myHandler() i want to get some values from asterisk database. I've tried to do it using Asterisk::AMI::Common::db_get(), but it just hangs until timeout and returns nothing, while in asterisk CLI i see that there is no manager connected. The only way i found is to make new AMI connection in myHandler() and use db_get(), but i think, that is bad way.  Can you help me?
I've also tried to send action 'DBGet' with send_action() with callback, it works well, i get the requested data, but I have no idea how to send this data back to function that called this action.

**Comment by rrb3942** [comment]
Hello,

Using 'DBGet' with send_action() and a callback is the right way to go when doing an event  based program, as anything else would cause blocking and all sorts of weird issues. 

It sounds to me like you need to create some sort of actionid to transaction/call mapping to continue processing after you get the callback with send_action. It is hard to give advice without seeing your code. 

I hang out in #perl on freenode.net so feel free to drop by and I will gladly try to help you out.

**Comment by beebeeep** [comment]
Big thanks for your help in IRC.
For this issue, there is two ways: first is to use blocking calls and  the second is to use some hash to store return value and continue processing into DBGet action callback
