### ISSUE TITLE
get_response does not contain response

### ISSUE THREAD

**Issue by vfstaboy** [rrb3942/perl-Asterisk-AMI#4]
Hello,
I'm trying to get familiar with your module so we can setup monitoring of our asterisk server.  Using  this script results in the following results.  Can someone explain what I'm doing wrong please?  Thank you

2
HASH(0x924720)
###### ######SCRIPT BEGIN
# !/usr/bin/perl -w

use Asterisk::AMI;
use Net::SSLeay;

my $astman = Asterisk::AMI->new(PeerAddr        =>      'host',
                                Username        =>      'user',
                                Secret          =>      'password',
                                UseSSL          =>      '1'
                        );

die "Unable to connect to asterisk" unless ($astman);

my $actionid = $astman->send_action({ Action => 'Command',
                                      Command => 'sip show peers'
                                    });

my $response = $astman->get_response($actionid);

print "$actionid\n";
print "$response\n";
###### ####SCRIPT END

-George

**Comment by rrb3942** [comment]
Hello George,

The response is returned as a Hash reference. For more information on references please refer to: http://perldoc.perl.org/perlref.html

You can use the Data::Dumper module to easily print the contents of the reference.

Try:

######SCRIPT BEGIN
!/usr/bin/perl -w

use Asterisk::AMI;
use Data::Dumper;
use Net::SSLeay;

my $astman = Asterisk::AMI->new(PeerAddr => 'host',

```
                        Username        =>      'user',
                        Secret          =>      'password',
                        UseSSL          =>      '1'
                );
```

die "Unable to connect to asterisk" unless ($astman);

my $actionid = $astman->send_action({ Action => 'Command',

```
                              Command => 'sip show peers'
                            });
```

my $response = $astman->get_response($actionid);

print "$actionid\n";
print DUMPER $response;
####SCRIPT END

You should also not need to explicitly use Net::SSLeay. It should get auto loaded for you whenever you enable SSL.

Also check out the sip_peers() method in Asterisk::AMI::Common. It also returns a hash reference but it organizes the output better.

http://search.cpan.org/~greenbean/Asterisk-AMI/lib/Asterisk/AMI/Common.pm

**Comment by vfstaboy** [comment]
Thank you!  That was the missing link for me.
