### ISSUE TITLE
recursive blocking wait detected

### ISSUE THREAD

**Issue by jamhed** [rrb3942/perl-Asterisk-AMI#5]
EV: error in callback (ignoring): AnyEvent::CondVar: recursive blocking wait detected at /usr/local/share/perl/5.10.1/Asterisk/AMI.pm line 1131

What's that supposed to mean?

**Comment by rrb3942** [comment]
Most likely you are calling a blocking method inside of a callback. For simulating blocking we run mini-event loops, so calling a blocking method means you are trying to run an event loop in an event loop which most things don't like.

If you can provide a code example that is causing this I could give you a better answer.

**Comment by jamhed** [comment]
Thanks for the reply. It seems I've figured it out -- my event handler writes to a database. If this procedure takes certain amount of time (how to figure out the exact value, by the way) I see that messages coming.

**Comment by rrb3942** [comment]
Thanks for the update. Might be worth looking at http://search.cpan.org/~mlehmann/AnyEvent-DBI-2.1/ for async database access to avoid blocking
