### ISSUE TITLE
AnyEvent->loop method removed

### ISSUE THREAD

**Issue by asolovjov** [rrb3942/perl-Asterisk-AMI#6]
I am new to perl programming trying to do some simple stuff with perl-Asterisk-AMI.
It might not be a bug but loop() method seems not to be working anymore. I've looked into AnyEvent code Impl::EV and noticed that sub loop has been removed about 3 months ago (Revision 1.23). It was actually removed from other AnyEvent implementations.

**Comment by rrb3942** [comment]
Good catch. Looks like it still works if you only have the pure-perl AnyEvent loop installed, but broke as soon as I tried another event loop (such as EV).

From the AnyEvent docs (and if you have AnyEvent loaded in the main program) you can try this instead:

AnyEvent->condvar->recv;

I will write up an actual fix once I can do some testing. Might add a loop_exit() method as well.

Thanks for the report!

**Comment by rrb3942** [comment]
Please try the new version with the loop method implemented via an AnyEvent conditional variable. You can download it via https://github.com/rrb3942/perl-Asterisk-AMI/tarball/master

If you don't mind please test and report if it works for your use case.

**Comment by asolovjov** [comment]
Well, my case is very simple :). I wrote a very simple manager event logger and used EV::loop. Then i tried to use $astman->loop() method and it didn't worked. I thought that it was due to some missing dependency but found out that loop code was commented.
I've tested new versions and it works. Thanks.

**Comment by rrb3942** [comment]
Thanks for the report. I will put out a release to cpan in the next few days that includes this fix.
